/**:    # autopilot and trajectory controller share some of the same parameters
    ros__parameters:
        # Autopilot gains
        roll_kp: 6.0
        roll_ki: 0.0
        roll_kd: 1.0
        pitch_kp: 6.0
        pitch_ki: 0.0
        pitch_kd: 1.0
        yaw_kp: 0.8
        yaw_ki: 0.002
        yaw_kd: 0.2

        roll_rate_kp: 0.5
        roll_rate_ki: 0.0
        roll_rate_kd: 0.0
        pitch_rate_kp: 0.5
        pitch_rate_ki: 0.0
        pitch_rate_kd: 0.0
        yaw_rate_kp: 0.5
        yaw_rate_ki: 0.0
        yaw_rate_kd: 0.0

        yaw_to_rate_kp: 2.0
        yaw_to_rate_ki: 0.0
        yaw_to_rate_kd: 0.2

        vel_n_P: 0.3
        vel_n_I: 0.01
        vel_n_D: 0.1
        vel_e_P: 0.3
        vel_e_I: 0.01
        vel_e_D: 0.1
        vel_d_P: 0.4
        vel_d_I: 0.25
        vel_d_D: 0.1

        n_P: 3.5
        n_I: 1.0
        n_D: 0.35
        e_P: 3.5
        e_I: 1.0
        e_D: 0.35
        d_P: 1.0
        d_I: 0.0
        d_D: 0.4

        # Saturation limits
        max_roll_rate: 1.0
        max_pitch_rate: 1.0
        max_yaw_rate: 1.0

        max_roll_torque: 10.0
        max_pitch_torque: 10.0
        max_yaw_torque: 10.0

        max_n_vel: 10.0
        max_e_vel: 10.0
        max_d_vel: 10.0

        max_throttle: 0.85
        min_throttle: 0.05

        max_roll: 30.0      # degrees
        max_pitch: 30.0     # degrees

        max_descend_accel: 1.0  # in g's
        max_descend_rate: 3.0

        down_command_window: 3.0

        # Trajectory controller gains
        u_n_kp: 0.5
        u_n_ki: 0.001
        u_n_kd: 0.5
        u_e_kp: 0.5
        u_e_ki: 0.001
        u_e_kd: 0.5
        u_d_kp: 4.0
        u_d_ki: 0.4
        u_d_kd: 4.0

        # Miscellanous
        tau: 0.05
        C_d: 0.0
        gravity: 9.81
        mass: 2.0
        equilibrium_throttle: 0.35

        # Takeoff and landing
        takeoff_d_pos: -10.0
        takeoff_height_threshold: 1.0
        takeoff_yaw: 0.0
        takeoff_d_vel: -0.5
        takeoff_landing_pos_hold_time: 3.0
        min_altitude_for_attitude_ctrl: 0.15
        max_descend_rate: 3.0
