# TODO: Clean up this file (split by node)
/**:    # autopilot and trajectory controller share some of the same parameters
    ros__parameters:
        # Autopilot gains
        roll_to_torque_kp: 7.0
        roll_to_torque_ki: 0.0
        roll_to_torque_kd: 1.0

        pitch_to_torque_kp: 7.0
        pitch_to_torque_ki: 0.0
        pitch_to_torque_kd: 1.0

        yaw_to_torque_kp: 2.0
        yaw_to_torque_ki: 0.002
        yaw_to_torque_kd: 1.0

        roll_rate_to_torque_kp: 0.5
        roll_rate_to_torque_ki: 0.0
        roll_rate_to_torque_kd: 0.0

        pitch_rate_to_torque_kp: 0.5
        pitch_rate_to_torque_ki: 0.0
        pitch_rate_to_torque_kd: 0.0

        yaw_rate_to_torque_kp: 0.5
        yaw_rate_to_torque_ki: 0.0
        yaw_rate_to_torque_kd: 0.0

        yaw_to_rate_kp: 4.0
        yaw_to_rate_ki: 0.0
        yaw_to_rate_kd: 2.0

        vel_n_to_accel_kp: 0.1
        vel_n_to_accel_ki: 0.01
        vel_n_to_accel_kd: 0.1

        vel_e_to_accel_kp: 0.1
        vel_e_to_accel_ki: 0.01
        vel_e_to_accel_kd: 0.1

        vel_d_to_accel_kp: 0.4
        vel_d_to_accel_ki: 0.01
        vel_d_to_accel_kd: 0.1

        pos_n_to_vel_kp: 0.5
        pos_n_to_vel_ki: 0.01
        pos_n_to_vel_kd: 0.1

        pos_e_to_vel_kp: 1.0
        pos_e_to_vel_ki: 0.01
        pos_e_to_vel_kd: 0.4

        pos_d_to_vel_kp: 1.0
        pos_d_to_vel_ki: 0.0
        pos_d_to_vel_kd: 0.4

        # Saturation limits
        max_roll_rate: 1.0
        max_pitch_rate: 1.0
        max_yaw_rate: 1.0

        max_roll_torque: 10.0
        max_pitch_torque: 10.0
        max_yaw_torque: 10.0

        max_n_vel: 10.0
        max_e_vel: 10.0
        max_d_vel: 10.0

        max_throttle: 0.85
        min_throttle: 0.3

        max_roll: 15.0      # degrees
        max_pitch: 15.0     # degrees

        max_descend_accel: 1.0  # in g's
        max_descend_rate: 3.0

        down_command_window: 3.0

        # Trajectory controller gains
        u_n_kp: 1.5
        u_n_ki: 0.01
        u_n_kd: 1.7
        u_e_kp: 1.5
        u_e_ki: 0.01
        u_e_kd: 1.7
        u_d_kp: 0.3
        u_d_ki: 0.0
        u_d_kd: 0.3

        # Miscellanous
        tau: 0.05
        C_d: 0.0
        gravity: 9.81
        mass: 3.5
        equilibrium_throttle: 0.65

        # Takeoff and landing
        takeoff_d_pos: -2.0
        takeoff_height_threshold: 1.0
        takeoff_yaw: 0.0
        takeoff_d_vel: -0.5
        takeoff_landing_pos_hold_time: 1.0
        min_altitude_for_attitude_ctrl: 0.15
        max_descend_rate: 3.0
