autopilot:
    ros__parameters:
        x_dot_P: 0.5
        x_dot_I: 0.0
        x_dot_D: 0.05
        y_dot_P: 0.5
        y_dot_I: 0.0
        y_dot_D: 0.05
        z_dot_P: 0.4
        z_dot_I: 0.25
        z_dot_D: 0.1
        north_P: 1.0
        north_I: 0.1
        north_D: 0.35
        east_P: 1.0
        east_I: 0.1
        east_D: 0.2
        down_P: 1.0
        down_I: 0.0
        down_D: 0.0
        psi_P: 2.0
        psi_I: 0.0
        psi_D: 0.0

        phi_kp: 0.002
        phi_ki: 0.0
        phi_kd: 0.002
        theta_kp: 0.002
        theta_ki: 0.0
        theta_kd: 0.002
        psi_kp: 0.2
        psi_ki: 0.0
        psi_kd: 0.2

        u_n_kp: 0.2
        u_n_ki: 0.0
        u_n_kd: 0.2
        max_u_n_dot: 5.0
        u_e_kp: 0.2
        u_e_ki: 0.0
        u_e_kd: 0.2
        max_u_e_dot: 5.0
        u_d_kp: 5.0
        u_d_ki: 0.001
        u_d_kd: 7.0
        max_u_d_dot: 25.0

        tau: 0.05
        C_d: 0.0
        gravity: 9.81
        mass: 2.0
        equilibrium_throttle: 0.45
        max_roll: 0.196
        max_pitch: 0.196
        max_yaw_rate: 0.785
        max_throttle: 0.85
        min_throttle: 0.05
        max_n_dot: 1.5
        max_e_dot: 1.5
        max_d_dot: 0.5
        max_roll_torque: 1.0
        max_pitch_torque: 1.0
        max_yaw_torque: 1.0
        min_altitude: 5.0
        max_thrust: 10.0    # kg
