controller:
    ros__parameters:
        x_dot_P: 0.5
        x_dot_I: 0.0
        x_dot_D: 0.05

        y_dot_P: 0.5
        y_dot_I: 0.0
        y_dot_D: 0.05

        z_dot_P: 0.4
        z_dot_I: 0.25
        z_dot_D: 0.1

        north_P: 1.0
        north_I: 0.1
        north_D: 0.35

        east_P: 1.0
        east_I: 0.1
        east_D: 0.2

        down_P: 1.0
        down_I: 0.0
        down_D: 0.0

        psi_P: 2.0
        psi_I: 0.0
        psi_D: 0.0

        tau: 0.05

        equilibrium_throttle: 0.5

        max_roll: 0.196
        max_pitch: 0.196
        max_yaw_rate: 0.785
        max_throttle: 0.85
        max_n_dot: 1.5
        max_e_dot: 1.5
        max_d_dot: 0.5

        min_altitude: 0.5

# estimator: {
#   ## Post-Process Information
#   bag_name: "~/roscopter_ws/src/bags/test.bag"
#   status_topic: "/status"
#   imu_topic: "/imu/data"
#   baro_topic: "/serial/baro"
#   range_topic: "/serial/laser"
#   pose_topic: ""
#   odom_topic: ""
#   gnss_topic: ""
#   ublox_gnss_topic: ""
#   inertial_sense_gnss_topic: "/ins/gps"
#   start_time: 0
#   duration: 1000
#   ## Is_flying checks
#   enable_arm_check: false # require armed before checking for is_flying
#   is_flying_threshold: 10.5 # if accel measurement exceed this magnitude, set is_flying
#   update_baro_velocity_threshold: 0.5
#   ## Logging
#   log_prefix: "/tmp/roscopter/ekf/"
#   enable_log: true
#   ## Measurement Processing
#   enable_partial_update: true
#   enable_out_of_order: false # TODO this isnt fully implemented
#   use_mocap: false
#   use_gnss: true
#   use_baro: true
#   use_range: false
#   use_zero_vel: true #publishes zeros for the estimator until the quad starts flying, prevents drift before flight
#   R_zero_vel: [0.001 0.001, 0.001, # vel
#                 0.001] # Altitude
#   ## Initial Uncertainty
#   P0: [10.0 10.0, 10.0, # pos
#       0.01 0.01, 0.01, # att
#       0.001 0.001, 0.001, # vel
#       0.01 0.01, 0.01, # accel bias
#       0.001 0.001, 0.001, # gyro bias
#       9.0           # baro bias
#       100.0] # reference altitude
#   ## Additive Process Noise
#   Qx: [0.000 0.000, 0.000,       # pos
#       0.000 0.000, 0.000,       # att
#       0.00001 0.00001, 0.00001,       # vel
#       0.0001 0.0001, 0.0001,       # accel bias
#       0.0001 0.0001, 0.0001,    # gyro bias
#       0.000001                    # baro bias
#       1.0]                       # reference altitude
#   ## Lambda (Partial Update)
#   # 1.0 = use full update
#   # 0.0 = do not update at all
#   lambda: [1.0 1.0, 1.0,       # pos
#           1.0 1.0, 1.0,       # att
#           1.0 1.0, 1.0,       # vel
#           0.1 0.1, 0.1,       # accel bias
#           0.1 0.1, 0.1,       # gyro bias
#           0.5                 # baro bias
#           0.3]                 # reference altitude
#   # Constant Parameeters
#   p_b2g: [0 0, 0], # position from body frame to gps frame
#   # Initial State
#   manual_ref_lla: false # Use manual ref_lla or use first lla from gps
#   ref_lla: [40.267320 -111.635629, 1387.0],
#   ref_heading: 0.0 # reference heading for inertial frame (from north)
#   x0: [0 0, 0,       # pos
#       1 0, 0, 0],    # att
#   ## Sensor Noise
#   #imu
#   accel_noise_stdev: 0.5
#   gyro_noise_stdev: 0.02
#   #Mocap
#   position_noise_stdev: 0.01 
#   attitude_noise_stdev: 0.01
#   #barometer 
#   baro_pressure_noise_stdev: 2.0
#   #range sensor
#   range_noise_stdev: 0.1
#   #gps
#   manual_gps_noise: false # choose noise params for GPS or use the values reported from the message topic
#   gps_horizontal_stdev: 0.021
#   gps_vertical_stdev: 0.04
#   gps_speed_stdev: 0.2
# }
